#!/usr/bin/python

import subprocess

ubuntu = ['git', 'openssh-server', 'joystick']
gazebo = ['ros-indigo-gazebo7-ros-pkgs', 'ros-indigo-gazebo7-ros-control']
ros = ['ros-indigo-perception', 'ros-indigo-robot', 'ros-indigo-viz']
ppa = ['sixad']
packages = ubuntu + gazebo + ros + ppa

subprocess.call("sudo sh -c 'echo \"deb http://packages.osrfoundation.org/gazebo/ubuntu-stable trusty main\" > /etc/apt/sources.list.d/gazebo-stable.list'", shell=True)
subprocess.call('wget -nv http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -', shell=True)
subprocess.call("sudo sh -c 'echo \"deb http://packages.ros.org/ros/ubuntu trusty main\" > /etc/apt/sources.list.d/ros-latest.list'", shell=True)
subprocess.call('wget -nv http://packages.ros.org/ros.key -O - | sudo apt-key add -', shell=True)
subprocess.call('sudo apt-add-repository -y ppa:falk-t-j/qtsixa', shell=True)

subprocess.call('sudo apt-get update'.split())

for package in packages:
    subprocess.call('sudo apt-get install {}'.format(package).split())

subprocess.call('sudo rosdep init'.split())
subprocess.call('rosdep update'.split())

subprocess.call('echo "source /opt/ros/indigo/setup.bash" >> ~/.bashrc', shell=True)
