#!/usr/bin/python

import subprocess

subprocess.call('echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros-latest.list'.split())
subprocess.call('wget -nv http://packages.ros.org/ros.key -O - | sudo apt-key add -'.split())
subprocess.call('echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" > /etc/apt/sources.list.d/gazebo-stable.list'.split())
subprocess.call('wget -nv http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -'.split())
subprocess.call('sudo apt-add-repository ppa:falk-t-j/qtsixa'.split())
subprocess.call('sudo apt-get update'.split())
subprocess.call('sudo apt-get install openssh-server joystick'.split())
subprocess.call('sudo apt-get install sixad'.split())
subprocess.call('sudo apt-get install ros-indigo-gazebo7-ros-pkgs'.split())
subprocess.call('sudo apt-get install ros-indigo-gazebo7-ros-control'.split())
subprocess.call('sudo apt-get install ros-indigo-perception'.split())
subprocess.call('sudo apt-get install ros-indigo-robot'.split())
subprocess.call('sudo apt-get install ros-indigo-viz'.split())
subprocess.call('sudo rosdep init'.split())
subprocess.call('rosdep update'.split())
subprocess.call('echo "source /opt/ros/indigo/setup.bash" >> ~/.bashrc'.split())
